# Generated by Django 3.1.3 on 2020-12-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
