# Generated by Django 2.1.4 on 2021-09-03 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0004_auto_20210903_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='age',
            field=models.IntegerField(default='None', validators=[django.core.validators.MinValueValidator(18)]),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other'), ('None', 'None')], default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='status',
            field=models.CharField(choices=[('single', 'single'), ('married', 'married'), ('widow', 'widow'), ('seprated', 'seprated'), ('commited', 'commited'), ('None', 'None')], default='None', max_length=20),
        ),
    ]
