# Generated by Django 2.1.4 on 2021-09-03 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0005_auto_20210903_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='age',
            field=models.IntegerField(default='18', validators=[django.core.validators.MinValueValidator(18)]),
        ),
    ]
