# Generated by Django 2.1.5 on 2021-09-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0006_auto_20210903_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='status',
            field=models.CharField(choices=[('single', 'single'), ('married', 'married'), ('None', 'None')], default='None', max_length=20),
        ),
    ]
