# Generated by Django 2.1.5 on 2021-09-20 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0007_auto_20210920_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='flag',
        ),
    ]
