# Generated by Django 2.1.5 on 2021-09-20 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0009_auto_20210920_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
