# Generated by Django 3.2.8 on 2021-10-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0012_auto_20210921_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
